### ISSUE TITLE
pymaging.incubator.formats.tests.PNGTests.test_non_indexed_interlaced fails in Python 3.x

### ISSUE THREAD

**Issue by ojii** [ojii/pymaging#11]
```
======================================================================
ERROR: test_non_indexed_interlaced (pymaging.incubator.formats.tests.PNGTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/workspace/pymaging/pymaging/incubator/formats/tests.py", line 56, in test_non_indexed_interlaced
    img = Image.open_from_path(_get_filepath('black-white-non-indexed-interlaced-adam7.png'))
  File "/home/jonas/workspace/pymaging/pymaging/image.py", line 62, in open_from_path
    return cls.open(fobj)
  File "/home/jonas/workspace/pymaging/pymaging/image.py", line 54, in open
    image = format.open(fileobj)
  File "/home/jonas/workspace/pymaging/pymaging/incubator/formats/png.py", line 37, in open
    return reader.get_image()
  File "/home/jonas/workspace/pymaging/pymaging/incubator/formats/png_reader.py", line 353, in get_image
    handler(chunk_data, chunk_length)
  File "/home/jonas/workspace/pymaging/pymaging/incubator/formats/png_reader.py", line 482, in handle_chunk_IHDR
    self.adam7 = Adam7(self)
  File "/home/jonas/workspace/pymaging/pymaging/incubator/formats/png_reader.py", line 244, in __init__
    self.init()
  File "/home/jonas/workspace/pymaging/pymaging/incubator/formats/png_reader.py", line 261, in init
    self.current_y = self.yiter.next()
AttributeError: 'itertools.islice' object has no attribute 'next'
```

**Comment by ojii** [comment]
Fixed in 0123713
